# -*- coding: utf-8 -*-
"""Live_Coding_codigoBase.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1WE6V1ehqArQicW7QGYZuFLVcGOftz2B8
"""

import pandas as pd
import plotly.express as px
import streamlit as st

# para rodar no computador:
# streamlit run

# lendo o dataset
df = pd.read_csv('https://raw.githubusercontent.com/wcota/covid19br/master/cases-brazil-states.csv')

# melhorando o nome das colunas da tabela
df = df.rename(columns={'newDeaths': 'Novos óbitos', 'newCases': 'Novos casos', 'deaths_per_100k_inhabitants': 'Óbitos por 100 mil habitantes', 'totalCases_per_100k_inhabitants': 'Casos por 100 mil habitantes'})

# seleção do estado
estados = list(df['state'].unique())
state = st.sidebar.selectbox('Qual estado? ', estados)
#state = 'ES'

#seleção da coluna
#column = 'Casos por 100 mil habitantes'
colunas = ['Novos óbitos', 'Novos casos', 'Óbitos por 100 mil habitantes', 'Casos por 100 mil habitantes']
column = st.sidebar.selectbox('Qual tipo de informação ', colunas)

# seleção das linhas que pertencem ao estado
df = df[df['state'] == state]

fig = px.line(df, x='date', y=column, title=column + ' - ' + state)
fig.update_layout( xaxis_title='Data', yaxis_title=column.upper(), title = {'x':0.5})

st.title('DADOS COVID - BRASIL')
st.write('Nesta aplicação o usuário tem a opção de escolher o estado e o tipo de informação para mostrar o gráfico. Utilize o menu lateral para alterar a mostragem.')


# fig.show()
st.plotly_chart(fig, use_container_width=True)

st.caption('Os dados foram obtidos do site: https://github.com/wcota/covid19br')